### ISSUE TITLE
Avoid the logrus use inside this project

### ISSUE THREAD

**Issue by leandro-lugaresi** [hellofresh/goengine#4]
The project is using log just for log some debug info/events. It's possible avoid this dependency?
Log is a application concern.
I believe that a better approach is the use of a some optional event hooks or just an interface  to be possible set the log by the application layer.

**Comment by vgarvardt** [comment]
fixed in https://github.com/hellofresh/goengine/issues/7

**Comment by leandro-lugaresi** [comment]
:1st_place_medal: Thanks!
